export const GET_CATEGORY_LIST = 'get_category_list'
export const GET_CATEGORY_SUB_LIST = 'get_category_sub_list'
export const GET_PRODUCT_LIST = 'get_product_list'
export const SET_USERS= 'set_users'
export const RESET_USER = 'reset_user'